name: smart_scheduler
channels:
  - defaults
  - conda-forge
dependencies:
  - asgiref=3.3.1
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - django=3.1.7
  - krb5=1.17.1
  - libcxx=10.0.0
  - libedit=3.1.20210216
  - libffi=3.3
  - libpq=12.2
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.0.1
  - psycopg2=2.8.6
  - python=3.7.10
  - pytz=2021.1
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.35.3
  - sqlparse=0.4.1
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11