# Generated by Django 3.1.7 on 2021-04-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
