# Generated by Django 3.1.7 on 2021-04-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_event_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_outdoors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
