# Generated by Django 3.1.2 on 2021-04-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20210411_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_high_pollen',
            field=models.BooleanField(default=False),
        ),
    ]
